# Generated by Django 3.1.3 on 2020-11-24 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201124_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='accounts.UserFollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
